export interface Exhibition {
  slug:        string;
  title:       string;
  subtitle:    string;
  dates:       string;
  startDate:   string;
  endDate:     string;
  location:    string;
  address:     string;
  city:        string;
  country:     string;
  image:       string;
  bannerImage: string;
  ticketPrice: { general: number; student: number; senior: number; child: number };
  openingHours:string;
  curator:     string;
  about:       string;
  highlights:  string[];
  tags:        string[];
  status:      "upcoming" | "ongoing" | "past";
}

export const EXHIBITIONS: Exhibition[] = [
  {
    slug:        "art-location-and-place-name",
    title:       "Art Location And Place Name",
    subtitle:    "Tapestries & Paintings from Bangladesh History",
    dates:       "September 18, 2026 – October 18, 2026",
    startDate:   "September 18, 2026",
    endDate:     "October 18, 2026",
    location:    "ArtHub Gallery — Main Hall",
    address:     "12 Gallery Road, Dhaka",
    city:        "Dhaka",
    country:     "Bangladesh",
    image:       "/images/exhibitions/exhibitions.png",
    bannerImage: "/images/exhibitions/exhibitions.png",
    ticketPrice: { general: 500, student: 250, senior: 300, child: 0 },
    openingHours:"Tuesday – Sunday, 10:00 am – 7:00 pm",
    curator:     "Dr. Farida Hossain",
    about:       "Especially for the occasion, ArtHub Gallery is setting up the tapestries and paintings from the series of Bangladesh history and the first tapestry from the series Our Blessed Lady of the Sablon.\n\nThis landmark exhibition brings together over 80 works spanning five centuries of artistic tradition, tracing the visual heritage of the Bengal delta from Mughal court painting through colonial-era prints to contemporary master works. Each piece has been carefully selected to reveal the continuities and ruptures that define the region's artistic identity.\n\nVisitors will move through six thematic rooms, each exploring a different chapter: land, river, devotion, resistance, everyday life and vision.",
    highlights:  ["80+ original works", "6 thematic galleries", "Interactive heritage map", "Guided tours daily at 11am & 4pm", "Catalogue available"],
    tags:        ["History", "Tapestry", "Painting", "Bangladesh"],
    status:      "upcoming",
  },
  {
    slug:        "masters-of-the-renaissance",
    title:       "Masters of the Renaissance",
    subtitle:    "Works from the Uffizi, Louvre and Private Collections",
    dates:       "November 3, 2026 – January 12, 2027",
    startDate:   "November 3, 2026",
    endDate:     "January 12, 2027",
    location:    "ArtHub Gallery — East Wing",
    address:     "12 Gallery Road, Dhaka",
    city:        "Dhaka",
    country:     "Bangladesh",
    image:       "/images/exhibitions/image 94.png",
    bannerImage: "/images/exhibitions/image 94.png",
    ticketPrice: { general: 800, student: 400, senior: 500, child: 150 },
    openingHours:"Tuesday – Sunday, 10:00 am – 8:00 pm",
    curator:     "Prof. Marco Bianchi",
    about:       "A landmark survey of Renaissance masters featuring works from the Uffizi, the Louvre and private collections — many on public display for the first time in decades.\n\nThe Renaissance — that extraordinary flowering of art, science and humanism in 15th and 16th century Europe — produced some of history's most celebrated works. This exhibition brings together 60 paintings, drawings and sculptures spanning the movement from its earliest stirrings in Florence through its spread across Italy and into Northern Europe.\n\nHighlights include studies by Raphael, preparatory drawings by Michelangelo's workshop, and three oil panels attributed to a direct follower of Leonardo da Vinci.",
    highlights:  ["60 works across 3 institutions", "Raphael studies on loan from Uffizi", "Michelangelo workshop drawings", "Conservation lab open to visitors Saturdays", "Audio guide in 6 languages"],
    tags:        ["Renaissance", "European", "Masters", "Historical"],
    status:      "upcoming",
  },
  {
    slug:        "contemporary-visions-south-asia",
    title:       "Contemporary Visions: South Asia",
    subtitle:    "Sixty Works Redefining South Asian Art",
    dates:       "February 20, 2027 – April 30, 2027",
    startDate:   "February 20, 2027",
    endDate:     "April 30, 2027",
    location:    "ArtHub Gallery — North Pavilion",
    address:     "12 Gallery Road, Dhaka",
    city:        "Dhaka",
    country:     "Bangladesh",
    image:       "/images/exhibitions/download (3).png",
    bannerImage: "/images/exhibitions/download (3).png",
    ticketPrice: { general: 600, student: 300, senior: 350, child: 100 },
    openingHours:"Wednesday – Monday, 9:00 am – 6:00 pm",
    curator:     "Ananya Chatterjee",
    about:       "Celebrating living artists from Bangladesh, India, Pakistan and Sri Lanka — sixty works that redefine what contemporary South Asian art looks like on the world stage.\n\nThis ambitious group exhibition gathers forty-two artists, many showing together for the first time, to ask: what does it mean to make art in South Asia today? The answers are as varied as the region itself — abstract canvases, photographic essays, video installations, textile works and monumental sculptures sit side by side in a deliberately non-hierarchical hang.\n\nThe exhibition is accompanied by a programme of artist talks, film screenings and workshops designed to deepen engagement with the works on view.",
    highlights:  ["42 living artists", "4 countries represented", "Mixed media installations", "Artist talks every Saturday", "Student workshop programme"],
    tags:        ["Contemporary", "South Asia", "Group Show", "Mixed Media"],
    status:      "upcoming",
  },
  {
    slug:        "light-and-shadow-modern-sculpture",
    title:       "Light & Shadow: Modern Sculpture",
    subtitle:    "Bronze, Glass and Steel Works from Six Countries",
    dates:       "May 10, 2027 – July 20, 2027",
    startDate:   "May 10, 2027",
    endDate:     "July 20, 2027",
    location:    "ArtHub Gallery — Sculpture Garden & Hall",
    address:     "12 Gallery Road, Dhaka",
    city:        "Dhaka",
    country:     "Bangladesh",
    image:       "/images/exhibitions/download (9).png",
    bannerImage: "/images/exhibitions/download (9).png",
    ticketPrice: { general: 700, student: 350, senior: 400, child: 100 },
    openingHours:"Tuesday – Sunday, 10:00 am – 7:00 pm",
    curator:     "Yuki Tanaka",
    about:       "An immersive exhibition exploring how contemporary sculptors use light as both material and metaphor — featuring monumental bronze, glass and steel works from six countries.\n\nSculpture has always been defined by its relationship to light — the way it catches on a polished surface, pools in shadow, or transforms entirely as the sun moves across the sky. This exhibition makes that relationship its explicit subject, with each of the 28 works selected specifically for how it behaves in changing light conditions.\n\nThe outdoor sculpture garden will be open for evening visits on Fridays and Saturdays, when solar-powered lighting creates a completely different experience of the works.",
    highlights:  ["28 sculptures across indoor & outdoor spaces", "Evening garden openings Fri–Sat", "Live bronze casting demonstration", "School group programme available", "Monumental steel installation by Lee Min-jun"],
    tags:        ["Sculpture", "Bronze", "Steel", "Glass", "Modern"],
    status:      "upcoming",
  },
  {
    slug:        "the-digital-canvas",
    title:       "The Digital Canvas",
    subtitle:    "Generative, AI-Assisted and Digital Paintings",
    dates:       "August 5, 2027 – October 1, 2027",
    startDate:   "August 5, 2027",
    endDate:     "October 1, 2027",
    location:    "ArtHub Gallery — Digital Lab & Main Hall",
    address:     "12 Gallery Road, Dhaka",
    city:        "Dhaka",
    country:     "Bangladesh",
    image:       "/images/exhibitions/download (10).png",
    bannerImage: "/images/exhibitions/download (10).png",
    ticketPrice: { general: 600, student: 300, senior: 350, child: 0 },
    openingHours:"Monday – Sunday, 10:00 am – 9:00 pm",
    curator:     "Priya Mehta",
    about:       "Where technology meets tradition — a curated selection of generative, AI-assisted and digital paintings printed on archival media, exploring the frontier of what art can be.\n\nWhat is a digital original? This exhibition confronts the question head-on, bringing together 50 works by artists who have made digital tools central to their practice — not as shortcuts, but as genuine media with their own aesthetics, limitations and possibilities.\n\nThe Digital Lab section invites visitors to interact with generative works in real time, while the main hall presents archival pigment prints and Diasec-mounted photographs at monumental scale. A companion programme of talks with artists, technologists and critics explores the ethics and aesthetics of AI in creative practice.",
    highlights:  ["50 digital works at large scale", "Interactive generative art station", "AI ethics discussion series", "Print-on-demand workshop Sundays", "Free entry for under-18s"],
    tags:        ["Digital", "Generative", "AI", "Technology", "Contemporary"],
    status:      "upcoming",
  },
  {
    slug:        "colours-of-the-delta",
    title:       "Colours of the Delta",
    subtitle:    "Watercolour Landscapes of Riverine Bangladesh",
    dates:       "October 25, 2027 – December 15, 2027",
    startDate:   "October 25, 2027",
    endDate:     "December 15, 2027",
    location:    "ArtHub Gallery — West Wing",
    address:     "12 Gallery Road, Dhaka",
    city:        "Dhaka",
    country:     "Bangladesh",
    image:       "/images/exhibitions/download (11).png",
    bannerImage: "/images/exhibitions/download (11).png",
    ticketPrice: { general: 400, student: 200, senior: 250, child: 0 },
    openingHours:"Tuesday – Sunday, 10:00 am – 6:00 pm",
    curator:     "Rashed Chowdhury",
    about:       "A celebration of Bangladesh's watercolour tradition — forty paintings capturing the rivers, haors and monsoon skies that define the country's visual identity.\n\nFrom Zainul Abedin's pioneering washes to contemporary plein-air painters working along the Meghna and Padma, this exhibition traces the watercolour landscape tradition that is uniquely Bangladeshi. Each work captures the light, humidity and sheer scale of a country shaped by water.\n\nThe exhibition includes a dedicated room for Sylheti haor landscapes and a live painting demonstration programme on weekends.",
    highlights:  ["40 watercolour landscapes", "Live painting demonstrations", "Haor landscapes gallery", "Plein-air workshop series", "Artist meet-and-greet Sundays"],
    tags:        ["Watercolour", "Landscape", "Bangladesh", "Rivers", "Tradition"],
    status:      "upcoming",
  },
  {
    slug:        "resistance-and-resilience-1971",
    title:       "Resistance & Resilience: Art of 1971",
    subtitle:    "Posters, Prints and Paintings from the Liberation War",
    dates:       "March 26, 2027 – June 15, 2027",
    startDate:   "March 26, 2027",
    endDate:     "June 15, 2027",
    location:    "Shilpakala Academy — Ground Floor",
    address:     "Segunbagicha, Dhaka",
    city:        "Dhaka",
    country:     "Bangladesh",
    image:       "/images/exhibitions/download (12).png",
    bannerImage: "/images/exhibitions/download (12).png",
    ticketPrice: { general: 300, student: 100, senior: 200, child: 0 },
    openingHours:"Sunday – Thursday, 10:00 am – 5:00 pm",
    curator:     "Prof. Nasreen Sultana",
    about:       "A powerful retrospective of visual art created during and about Bangladesh's Liberation War of 1971 — propaganda posters, woodcut prints, protest paintings and documentary photographs.\n\nArt was a weapon in 1971. Artists created posters that mobilised a nation, woodcuts that documented atrocities, and paintings that channelled grief into resistance. This exhibition brings together over 100 rarely-seen works from private collections, university archives and the Liberation War Museum.\n\nThe exhibition opens on Independence Day and is accompanied by a documentary film screening series and oral history recordings from surviving artists.",
    highlights:  ["100+ works from 1971", "Rare propaganda posters", "Liberation War Museum loans", "Documentary film screenings", "Oral history recordings"],
    tags:        ["Liberation War", "1971", "Political Art", "Bangladesh History", "Prints"],
    status:      "upcoming",
  },
  {
    slug:        "new-voices-emerging-artists-2027",
    title:       "New Voices: Emerging Artists 2027",
    subtitle:    "Twenty Artists Under Thirty Redefining Bangladeshi Art",
    dates:       "January 15, 2027 – March 10, 2027",
    startDate:   "January 15, 2027",
    endDate:     "March 10, 2027",
    location:    "Bengal Gallery of Fine Arts",
    address:     "Gulshan, Dhaka",
    city:        "Dhaka",
    country:     "Bangladesh",
    image:       "/images/exhibitions/download (13).png",
    bannerImage: "/images/exhibitions/download (13).png",
    ticketPrice: { general: 400, student: 150, senior: 250, child: 0 },
    openingHours:"Tuesday – Saturday, 11:00 am – 7:00 pm",
    curator:     "Tahmina Akter",
    about:       "The most exciting young artists in Bangladesh — twenty painters, sculptors and mixed-media artists under thirty, each showing a body of work that points to where Bangladeshi art is heading next.\n\nSelected from over 400 submissions by a jury of established artists and curators, these twenty artists represent the diversity and ambition of a new generation. Their work engages with climate change, digital identity, gender politics, urbanisation and the tension between tradition and modernity.\n\nSeveral works are available for purchase through ArtHub, with 100% of proceeds going directly to the artists.",
    highlights:  ["20 emerging artists", "Selected from 400+ submissions", "Works available on ArtHub", "Opening night panel discussion", "Artist studio visits programme"],
    tags:        ["Emerging", "Young Artists", "Contemporary", "Bangladesh", "Group Show"],
    status:      "upcoming",
  },
  {
    slug:        "terracotta-traditions-bengal",
    title:       "Terracotta Traditions of Bengal",
    subtitle:    "Ancient Clay Art from Temples to Contemporary Studios",
    dates:       "April 5, 2027 – June 30, 2027",
    startDate:   "April 5, 2027",
    endDate:     "June 30, 2027",
    location:    "National Museum — Gallery 3",
    address:     "Shahbag, Dhaka",
    city:        "Dhaka",
    country:     "Bangladesh",
    image:       "/images/exhibitions/download (14).png",
    bannerImage: "/images/exhibitions/download (14).png",
    ticketPrice: { general: 200, student: 50, senior: 100, child: 0 },
    openingHours:"Saturday – Wednesday, 9:30 am – 5:00 pm",
    curator:     "Dr. Mostafa Kamal",
    about:       "Bengal's terracotta tradition stretches back over two thousand years — from the ornate temple panels of Paharpur and Mainamati to the pottery and sculpture being made in village workshops today.\n\nThis exhibition brings together archaeological fragments, temple panel reproductions, traditional pottery and contemporary terracotta sculpture to trace an unbroken line of clay craftsmanship across the centuries. Highlights include a reconstructed section of the Somapura Mahavihara terracotta frieze and live pottery demonstrations by master craftsmen from Rajshahi.\n\nA companion workshop series teaches visitors basic hand-building and wheel-throwing techniques.",
    highlights:  ["Archaeological terracotta fragments", "Paharpur frieze reconstruction", "Live pottery demonstrations", "Hands-on clay workshop", "Contemporary sculpture gallery"],
    tags:        ["Terracotta", "Pottery", "Ancient Art", "Bengal", "Craft"],
    status:      "upcoming",
  },
  {
    slug:        "beyond-borders-diaspora-art",
    title:       "Beyond Borders: Bangladeshi Diaspora Art",
    subtitle:    "Artists Working Between Cultures and Continents",
    dates:       "July 1, 2027 – September 20, 2027",
    startDate:   "July 1, 2027",
    endDate:     "September 20, 2027",
    location:    "ArtHub Gallery — All Galleries",
    address:     "12 Gallery Road, Dhaka",
    city:        "Dhaka",
    country:     "Bangladesh",
    image:       "/images/exhibitions/download (15).png",
    bannerImage: "/images/exhibitions/download (15).png",
    ticketPrice: { general: 550, student: 275, senior: 350, child: 100 },
    openingHours:"Tuesday – Sunday, 10:00 am – 7:00 pm",
    curator:     "Shirin Ahmed",
    about:       "Thirty Bangladeshi-born artists living and working in London, New York, Tokyo, Sydney and beyond — their work explores identity, displacement, nostalgia and the creative tension of belonging to two cultures simultaneously.\n\nWhat happens when a Bangladeshi artist makes work in Brooklyn? In East London? In Melbourne? This exhibition argues that diaspora artists occupy a unique creative space — rooted in Bengali visual traditions but shaped by the aesthetics and conversations of their adopted homes.\n\nThe result is work that is neither purely Bangladeshi nor purely Western — it is something new, and it is some of the most exciting art being made today.",
    highlights:  ["30 diaspora artists", "5 continents represented", "Video art installation room", "Skype artist talks with overseas artists", "Bilingual catalogue (Bengali/English)"],
    tags:        ["Diaspora", "Identity", "International", "Contemporary", "Mixed Media"],
    status:      "upcoming",
  },
  {
    slug:        "miniature-worlds-south-asian-painting",
    title:       "Miniature Worlds: South Asian Painting Traditions",
    subtitle:    "Mughal, Rajput and Bengali Miniatures from Private Collections",
    dates:       "November 15, 2027 – February 28, 2028",
    startDate:   "November 15, 2027",
    endDate:     "February 28, 2028",
    location:    "ArtHub Gallery — East Wing",
    address:     "12 Gallery Road, Dhaka",
    city:        "Dhaka",
    country:     "Bangladesh",
    image:       "/images/exhibitions/download (16).png",
    bannerImage: "/images/exhibitions/download (16).png",
    ticketPrice: { general: 650, student: 300, senior: 400, child: 100 },
    openingHours:"Tuesday – Sunday, 10:00 am – 7:00 pm",
    curator:     "Dr. Amrita Sen",
    about:       "The miniature painting traditions of South Asia represent some of the most technically accomplished and visually stunning art ever made — intricate scenes painted with single-hair brushes on surfaces no larger than a book page.\n\nThis exhibition brings together forty miniatures from Mughal, Rajput and Bengali traditions, many from private collections and never previously exhibited publicly. Visitors can examine the extraordinary detail through magnifying stations and a digital zoom gallery.\n\nThe accompanying programme includes a masterclass in miniature painting technique by contemporary practitioners keeping the tradition alive.",
    highlights:  ["40 miniature paintings", "Digital zoom gallery", "Magnifying examination stations", "Miniature painting masterclass", "Private collection loans"],
    tags:        ["Miniature", "Mughal", "Traditional", "South Asian", "Painting"],
    status:      "upcoming",
  },
];
