export interface ShopData {
  slug: string;
  displayName: string;
  ownerName: string;
  location: string;
  district: string;
  division: string;
  phone: string;
  email: string;
  websiteUrl?: string;
  instagramUrl?: string;
  facebookUrl?: string;
  ratingAvg: number;
  totalSales: number;
  artworkCount: number;
  reviewCount: number;
  isFeatured: boolean;
  isApproved: boolean;
  memberSince: string;
  responseTime: string;
  specialty: string;
  bio: string;
  bannerUrl: string;
  logoUrl: string | null;
}

export const ALL_SHOPS: ShopData[] = [
  {
    slug: "dhaka-canvas",
    displayName: "Dhaka Canvas",
    ownerName: "Rahim Uddin Ahmed",
    location: "Dhanmondi, Dhaka",
    district: "Dhaka",
    division: "Dhaka",
    phone: "+880 1711-234567",
    email: "contact@dhakacanvas.com.bd",
    websiteUrl: "https://dhakacanvas.com.bd",
    instagramUrl: "@dhakacanvas",
    facebookUrl: "fb.com/dhakacanvas",
    ratingAvg: 4.9,
    totalSales: 134,
    artworkCount: 41,
    reviewCount: 98,
    isFeatured: true,
    isApproved: true,
    memberSince: "2021",
    responseTime: "Replies within 2 hours",
    specialty: "Oil Paintings",
    bio: "Dhaka Canvas is the studio of Rahim Uddin Ahmed, one of Dhaka's most celebrated contemporary oil painters. His work is deeply rooted in the cultural heritage of Bangladesh — from the misty rivers of the Sundarbans to the vibrant streets of old Dhaka.\n\nRahim trained at the Faculty of Fine Arts, University of Dhaka, and has exhibited across South Asia, including shows in Kolkata, Mumbai, and Kathmandu. Each painting is hand-stretched and signed, and comes with a certificate of authenticity.",
    bannerUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1600",
    logoUrl: null,
  },
  {
    slug: "ruposhi-art",
    displayName: "Ruposhi Art",
    ownerName: "Fatema Begum",
    location: "Gulshan, Dhaka",
    district: "Dhaka",
    division: "Dhaka",
    phone: "+880 1812-345678",
    email: "ruposhiart@gmail.com",
    instagramUrl: "@ruposhi.art",
    facebookUrl: "fb.com/ruposhiart",
    ratingAvg: 4.7,
    totalSales: 87,
    artworkCount: 28,
    reviewCount: 61,
    isFeatured: false,
    isApproved: true,
    memberSince: "2022",
    responseTime: "Replies within 4 hours",
    specialty: "Watercolor",
    bio: "Ruposhi Art celebrates the natural beauty of Bangladesh through delicate watercolor paintings. Fatema Begum draws inspiration from the haor wetlands, the mustard fields of Jessore, and the rice paddies that stretch across the Bengal delta.\n\nSelf-taught over fifteen years, Fatema's works have been featured in Dhaka's National Museum gallery and collected by art lovers across Bangladesh and the diaspora.",
    bannerUrl: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=1600",
    logoUrl: null,
  },
  {
    slug: "chittagong-art-house",
    displayName: "Chittagong Art House",
    ownerName: "Kamal Hossain Chowdhury",
    location: "Agrabad, Chittagong",
    district: "Chittagong",
    division: "Chittagong",
    phone: "+880 1913-456789",
    email: "info@chittagongartouse.com",
    websiteUrl: "https://chittagongartouse.com",
    instagramUrl: "@ctgartouse",
    ratingAvg: 4.8,
    totalSales: 112,
    artworkCount: 36,
    reviewCount: 79,
    isFeatured: true,
    isApproved: true,
    memberSince: "2020",
    responseTime: "Replies within 3 hours",
    specialty: "Acrylic",
    bio: "Chittagong Art House is Bangladesh's premier port-city art studio. Kamal Hossain Chowdhury brings the raw energy of Chittagong's shipbreaking yards, fishing docks, and hill tracts into bold acrylic compositions that command attention.\n\nKamal studied at the Chittagong Government Museum School of Art and has had solo exhibitions in Singapore and Malaysia. His works explore industrial beauty and human resilience.",
    bannerUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1600",
    logoUrl: null,
  },
  {
    slug: "sylhet-strokes",
    displayName: "Sylhet Strokes",
    ownerName: "Nusrat Jahan",
    location: "Zindabazar, Sylhet",
    district: "Sylhet",
    division: "Sylhet",
    phone: "+880 1614-567890",
    email: "sylhetstrokes@outlook.com",
    facebookUrl: "fb.com/sylhetstrokes",
    ratingAvg: 4.6,
    totalSales: 54,
    artworkCount: 19,
    reviewCount: 38,
    isFeatured: false,
    isApproved: true,
    memberSince: "2023",
    responseTime: "Replies within 6 hours",
    specialty: "Gouache",
    bio: "Sylhet Strokes brings the lush tea gardens, cascading waterfalls, and misty hills of Sylhet to life through vibrant gouache paintings. Nusrat Jahan grew up among the tea estates of Moulvibazar and paints from memory and love.\n\nHer work has been displayed at the Sylhet Divisional Cultural Centre and she regularly hosts painting workshops for young artists in the region.",
    bannerUrl: "https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=1600",
    logoUrl: null,
  },
  {
    slug: "rajshahi-ranga",
    displayName: "Rajshahi Ranga",
    ownerName: "Mohammad Abdur Razzaq",
    location: "Shaheb Bazar, Rajshahi",
    district: "Rajshahi",
    division: "Rajshahi",
    phone: "+880 1515-678901",
    email: "rajshahiranga@gmail.com",
    instagramUrl: "@rajshahiranga",
    ratingAvg: 4.8,
    totalSales: 76,
    artworkCount: 32,
    reviewCount: 54,
    isFeatured: true,
    isApproved: true,
    memberSince: "2021",
    responseTime: "Replies within 2 hours",
    specialty: "Oil Paintings",
    bio: "Rajshahi Ranga captures the golden landscapes of north Bengal — the sprawling mango orchards, the ancient Paharpur ruins, and the mighty Padma River at sunset. Mohammad Abdur Razzaq is a professor of fine arts at Rajshahi University and has been painting for over 25 years.\n\nHis classical oil technique combined with distinctly Bangladeshi subject matter has earned him national recognition, including the Bangladesh Shilpakala Academy Award.",
    bannerUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=1600",
    logoUrl: null,
  },
  {
    slug: "coastal-lens-cox",
    displayName: "Coastal Lens Cox",
    ownerName: "Taslima Akter",
    location: "Cox's Bazar Sadar",
    district: "Cox's Bazar",
    division: "Chittagong",
    phone: "+880 1716-789012",
    email: "coastallens@cox.art",
    websiteUrl: "https://coastallens.art",
    instagramUrl: "@coastallenscox",
    ratingAvg: 4.9,
    totalSales: 63,
    artworkCount: 24,
    reviewCount: 47,
    isFeatured: false,
    isApproved: true,
    memberSince: "2022",
    responseTime: "Replies within 3 hours",
    specialty: "Photography",
    bio: "Coastal Lens Cox is the photographic art studio of Taslima Akter, based at the world's longest natural sea beach. Her large-format prints capture Cox's Bazar in ways tourists never see — dawn mist over Inani, fishermen hauling nets at Teknaf, and children playing in the surf at golden hour.\n\nAll prints are produced on museum-grade archival paper and available in signed limited editions of 25.",
    bannerUrl: "https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=1600",
    logoUrl: null,
  },
  {
    slug: "khulna-florals",
    displayName: "Khulna Florals",
    ownerName: "Rina Devi Roy",
    location: "Khalishpur, Khulna",
    district: "Khulna",
    division: "Khulna",
    phone: "+880 1817-890123",
    email: "khulnaflorals@yahoo.com",
    facebookUrl: "fb.com/khulnaflorals",
    ratingAvg: 4.9,
    totalSales: 91,
    artworkCount: 33,
    reviewCount: 67,
    isFeatured: true,
    isApproved: true,
    memberSince: "2021",
    responseTime: "Replies within 2 hours",
    specialty: "Photography",
    bio: "Khulna Florals is a fine art photography studio celebrating the extraordinary flora of the Sundarbans region and the Khulna countryside. Rina Devi Roy has spent a decade photographing mangrove orchids, water lilies, and the rare Bengal tiger's habitat.\n\nHer work has been exhibited at the Bangladesh National Museum and licensed by WWF Bangladesh for conservation campaigns. Each print comes with a portion of proceeds going to Sundarbans preservation.",
    bannerUrl: "https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?w=1600",
    logoUrl: null,
  },
  {
    slug: "barisal-abstract",
    displayName: "Barisal Abstract",
    ownerName: "Sumon Chandra Das",
    location: "Band Road, Barisal",
    district: "Barisal",
    division: "Barisal",
    phone: "+880 1518-901234",
    email: "barisalabstract@gmail.com",
    instagramUrl: "@barisal.abstract",
    ratingAvg: 4.5,
    totalSales: 43,
    artworkCount: 17,
    reviewCount: 29,
    isFeatured: false,
    isApproved: true,
    memberSince: "2023",
    responseTime: "Replies within 8 hours",
    specialty: "Acrylic",
    bio: "Barisal Abstract brings the rhythm of the river delta to geometric abstraction. Sumon Chandra Das grew up watching hundreds of rivers meet and diverge around Barisal city, and that flowing, interlocking geometry defines his acrylic works.\n\nSumon holds a BFA from the Dhaka University Faculty of Fine Arts and teaches at a local art school while maintaining a studio practice.",
    bannerUrl: "https://images.unsplash.com/photo-1515405295579-ba7b45403062?w=1600",
    logoUrl: null,
  },
  {
    slug: "mymensingh-ink",
    displayName: "Mymensingh Ink",
    ownerName: "Sharmin Nahar",
    location: "Ganginarpar, Mymensingh",
    district: "Mymensingh",
    division: "Mymensingh",
    phone: "+880 1619-012345",
    email: "mymensinghink@gmail.com",
    facebookUrl: "fb.com/mymensinghink",
    ratingAvg: 4.7,
    totalSales: 58,
    artworkCount: 22,
    reviewCount: 41,
    isFeatured: false,
    isApproved: true,
    memberSince: "2022",
    responseTime: "Replies within 5 hours",
    specialty: "Mixed Media",
    bio: "Mymensingh Ink blends traditional Bengali folk art motifs with contemporary mixed media techniques. Sharmin Nahar draws from the Jamdani weaving patterns of her hometown and the ancient terracotta art of the Brahmaputra region.\n\nHer works have been shortlisted for the Bangladesh Shilpakala Academy Young Artist Award and are held in private collections in Dhaka, London, and New York.",
    bannerUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=1600",
    logoUrl: null,
  },
  {
    slug: "pixel-dhaka",
    displayName: "Pixel Dhaka",
    ownerName: "Arif Hasan Siddiqui",
    location: "Banani, Dhaka",
    district: "Dhaka",
    division: "Dhaka",
    phone: "+880 1720-123456",
    email: "arif@pixeldhaka.com",
    websiteUrl: "https://pixeldhaka.com",
    instagramUrl: "@pixeldhaka",
    facebookUrl: "fb.com/pixeldhaka",
    ratingAvg: 4.8,
    totalSales: 108,
    artworkCount: 52,
    reviewCount: 83,
    isFeatured: true,
    isApproved: true,
    memberSince: "2020",
    responseTime: "Replies within 1 hour",
    specialty: "Digital Art",
    bio: "Pixel Dhaka is Bangladesh's leading digital art studio. Arif Hasan Siddiqui trained as a graphic designer and transitioned to digital fine art in 2018, pioneering a style that fuses Mughal miniature influences with contemporary digital illustration.\n\nHis limited-edition prints — each signed and numbered — are collected by tech entrepreneurs and art patrons across Southeast Asia. Arif also runs Bangladesh's largest online digital art community with 45,000+ members.",
    bannerUrl: "https://images.unsplash.com/photo-1620421680010-0766ff230392?w=1600",
    logoUrl: null,
  },
  {
    slug: "rangpur-fluid",
    displayName: "Rangpur Fluid",
    ownerName: "Halima Khatun",
    location: "Station Road, Rangpur",
    district: "Rangpur",
    division: "Rangpur",
    phone: "+880 1521-234567",
    email: "rangpurfluid@outlook.com",
    facebookUrl: "fb.com/rangpurfluid",
    ratingAvg: 4.6,
    totalSales: 47,
    artworkCount: 18,
    reviewCount: 32,
    isFeatured: false,
    isApproved: true,
    memberSince: "2023",
    responseTime: "Replies within 6 hours",
    specialty: "Mixed Media",
    bio: "Rangpur Fluid explores movement, balance, and flow through ink and mixed media. Halima Khatun is inspired by the floodwaters of the Teesta River that define life in northern Bangladesh — their power, their unpredictability, and their quiet beauty after the monsoon recedes.\n\nHalima is a graduate of the Rajshahi University of Engineering and Technology's design department and splits her time between studio work and community art education.",
    bannerUrl: "https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=1600",
    logoUrl: null,
  },
  {
    slug: "comilla-heritage",
    displayName: "Comilla Heritage Art",
    ownerName: "Zahirul Islam",
    location: "Kandirpar, Comilla",
    district: "Comilla",
    division: "Chittagong",
    phone: "+880 1622-345678",
    email: "comillaheritage@gmail.com",
    instagramUrl: "@comilla.heritage",
    facebookUrl: "fb.com/comillaheritrage",
    ratingAvg: 4.9,
    totalSales: 49,
    artworkCount: 16,
    reviewCount: 35,
    isFeatured: false,
    isApproved: true,
    memberSince: "2022",
    responseTime: "Replies within 4 hours",
    specialty: "Oil Paintings",
    bio: "Comilla Heritage Art specialises in classical oil paintings depicting the ancient archaeological wonders of Bangladesh — the Buddhist monasteries of Mainamati, the medieval fortresses of Comilla, and the vanishing rural landscapes of eastern Bengal.\n\nZahirul Islam holds a master's degree in Fine Arts from Jahangirnagar University and has collaborated with Bangladesh's Department of Archaeology to document historical sites through painting.",
    bannerUrl: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=1600",
    logoUrl: null,
  },
];

export function getShopBySlug(slug: string): ShopData | undefined {
  return ALL_SHOPS.find((s) => s.slug === slug);
}
